### ISSUE TITLE
Do *not* end \item with \\.

### ISSUE THREAD

**Issue by vermiculus** [osener/markup.rocks#2]
Issue's in the title, really. _Do not do this._

**Comment by vermiculus** [comment]
Unless this is really a Pandoc issue, at which point I am simultaneously ashamed and enraged. :smile:

**Comment by ozanvos** [comment]
Can you post an example document and point out the problem?

**Comment by vermiculus** [comment]
Huh, it doesn't seem to do this anymore. Did you recently update pandoc? (And given that you use pandoc internally to do the conversion, I don't see it as your issue anyway.)

**Comment by ozanvos** [comment]
That's odd. Please let me know if you see this happen again, I can try fixing this at the editor level.

**Comment by vermiculus** [comment]
If I ever see it again, I'll take whatever kind of snapshot information I can find and give you the heads-up :)
