### ISSUE TITLE
Equivalent transformations don't obey identity

### ISSUE THREAD

**Issue by vermiculus** [osener/markup.rocks#3]
The minimal LaTeX document

``` tex
\documentclass{article}
\begin{document}
hello, world
\end{document}
```

yields

``` tex
hello, world
```

under LaTeX–LaTeX.

**Comment by vermiculus** [comment]
Unless this is really a Pandoc issue, at which point I am simultaneously ashamed and enraged. :smile: If this is just noise, I apologize :)

**Comment by ozanvos** [comment]
This is the behavior of Pandoc and I think it's normal that some information to be lost as Pandoc's intermediate representation is not geared towards a complex format like LaTeX. I thought about bypassing Pandoc when source and target are the same but then it wouldn't provide any benefit to the user. At least right now you can use this to get a cleanly formatted document.

**Comment by vermiculus** [comment]
What about filtering the source format from the list of destination formats? That could bypass the issue altogether and would simplify the UI.

**Comment by ozanvos** [comment]
I'm still hoping someone can get a legitimate use out of this :)

**Comment by vermiculus** [comment]
Oh I see -- I misunderstood/misread your original reply :) I guess that's a fair use-case, even if a little irksome as a mathematician :)

As for the general tool, I do think there's a pretty broad use-case for it. Just look at some of the online compilers for LaTeX -- you'll pry TeX Live from my dead, gnarled emacs fingers, but the online solution has been gaining a lot of inertia. It'll be interesting to see where all this takes us.
