### ISSUE TITLE
Extracting pandoc js npm/api version

### ISSUE THREAD

**Issue by jeroen** [osener/markup.rocks#5]
I'm interested in the javascript build of Pandoc to use in embedded javascript environments (node, v8, etc). Have you considered providing this separately from your front-end through npm or whatever?

**Comment by ozanvos** [comment]
This is beyond the scope of this project but I would gladly merge it in if you sent a pull request to [my pandoc fork](https://github.com/osener/pandoc) containing a JS API wrapper exposing Pandoc functionality.
