### ISSUE TITLE
Option of building only selected components from make

### ISSUE THREAD

**Issue by Immortalin** [osener/markup.rocks#8]
Hi, I wish to build only features for converting between a few selected formats e.g. word to PDF only so as to save space and remove any unnecessary features. Can an option be added to the makefile?

**Comment by ozanvos** [comment]
This is not a feature I intend to implement as most of the supported languages have few dependencies and removing support for them won't make a big effect on the file size. Also, neither Word nor PDF are supported as source or result formats in markup.rocks.
